- name: Install aptitude using apt
  apt:
    state: latest
    update_cache: yes
    force_apt_get: yes
    pkg:
      - aptitude

- name: Install required system packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
