- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu disco stable
    state: present

- name: Install docker-ce
  apt: 
    update_cache: yes
    state: latest
    pkg:
      - docker-ce
